### ISSUE TITLE
表情支持

### ISSUE THREAD

**Issue by fakefred** [cogons/issvue#2]
![deepinscreenshot_select-area_20180119174146](https://user-images.githubusercontent.com/19605886/35144646-10eacf40-fd40-11e7-9ccf-812830846d80.png)
^ 截圖
`:new_moon_with_face:` 應該出現 :new_moon_with_face: 的效果，但是 issvue 的 markdown 不支持顯示。

REPRODUCING: issue 中用 :$EMOJI_NAME: 插入表情符號，在 issvue 中顯示。
REQUEST: 增加表情支持

**Comment by cogons** [comment]
已修复，多谢！
